name: Publish to CodeArtifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  publish-package:
    uses: tavily-ai/github-actions/.github/workflows/pypi-codeartifact-deploy.yml@feat/add-pypi
    with:
      python_version: '3.11'
      package_directory: '.'
      codeartifact_domain: 'tavily'
      codeartifact_repository: 'tavily-internal-packages'
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      PERSONAL_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
      UTILS_ACCOUNT_ID: ${{ secrets.UTILS_ACCOUNT_ID }}
